version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/testingp2
    ports:
      - "3000:3000"
    depends_on:
      - db

  # selenium:
  #   image: selenium/standalone-chrome-debug:3.0.1-germanium
  #     # Debug version enables VNC ability
  #   ports: ['4444:4444', '5900:5900']
  #     # Bind selenium port & VNC port
  #   logging:
  #     driver: none
  #     # Disable noisy logs.